/// <reference types="cypress" />

export function setupDefaultMocks(): void {
  cy.intercept('POST', '**/rest/v1/rpc/get_match_list', {
    statusCode: 200,
    body: [
      {
        match_id: 'wc-2026-g1',
        home_team_name: 'Mexique',
        home_team_code: 'MEX',
        home_team_flag: 'https://flagcdn.com/w320/mx.png',
        away_team_name: 'Canada',
        away_team_code: 'CAN',
        away_team_flag: 'https://flagcdn.com/w320/ca.png',
        kickoff_at: '2026-06-14T17:00:00Z',
        stage: 'group',
        group_name: 'A',
        status: 'scheduled',
        user_home_score: 2,
        user_away_score: 1,
        user_is_boosted: false,
        result_home_score: null,
        result_away_score: null,
        points_earned: null,
      },
      {
        match_id: 'wc-2026-g2',
        home_team_name: 'France',
        home_team_code: 'FRA',
        home_team_flag: 'https://flagcdn.com/w320/fr.png',
        away_team_name: 'Angleterre',
        away_team_code: 'ENG',
        away_team_flag: 'https://flagcdn.com/w320/gb-eng.png',
        kickoff_at: '2026-06-14T20:00:00Z',
        stage: 'group',
        group_name: 'B',
        status: 'scheduled',
        user_home_score: null,
        user_away_score: null,
        user_is_boosted: null,
        result_home_score: null,
        result_away_score: null,
        points_earned: null,
      },
      {
        match_id: 'wc-2026-g3',
        home_team_name: 'Portugal',
        home_team_code: 'POR',
        home_team_flag: 'https://flagcdn.com/w320/pt.png',
        away_team_name: 'Maroc',
        away_team_code: 'MAR',
        away_team_flag: 'https://flagcdn.com/w320/ma.png',
        kickoff_at: '2026-06-15T18:00:00Z',
        stage: 'group',
        group_name: 'C',
        status: 'locked',
        user_home_score: 1,
        user_away_score: 1,
        user_is_boosted: false,
        result_home_score: null,
        result_away_score: null,
        points_earned: null,
      },
      {
        match_id: 'wc-2026-g4',
        home_team_name: 'Argentine',
        home_team_code: 'ARG',
        home_team_flag: 'https://flagcdn.com/w320/ar.png',
        away_team_name: 'États-Unis',
        away_team_code: 'USA',
        away_team_flag: 'https://flagcdn.com/w320/us.png',
        kickoff_at: '2026-06-10T16:00:00Z',
        stage: 'group',
        group_name: 'D',
        status: 'finished',
        user_home_score: 3,
        user_away_score: 2,
        user_is_boosted: false,
        result_home_score: 3,
        result_away_score: 1,
        points_earned: 100,
      },
    ],
  }).as('getMatchList');

  cy.intercept('POST', '**/rest/v1/rpc/get_user_profile', {
    statusCode: 200,
    body: {
      total_points: 1240,
      exact_count: 5,
      total_predictions: 20,
      rank: 4,
      favorite_team_id: null,
      favorite_team_code: null,
      favorite_team_name: null,
      favorite_team_flag: null,
      username: null,
    },
  }).as('getUserProfile');

  cy.intercept('POST', '**/rest/v1/rpc/upsert_prediction', {
    statusCode: 200,
    body: { success: true },
  }).as('upsertPrediction');
}
